name: HPSBR-Base
version: 0.1
api-version: 1.13
author: Sucukya
main: me.sucukya.Main
commands:
  refresh:
    usage: /refresh
    description: Refresh the Config
  base:
    usage: /base <stat> <add,remove,set> <Player> <Amount>
    description: Edit base stats!
  build:
    usage: /build
    description: Turn  Buildmode on/off!
  gm:
    usage: /gm <1,2,3,0>
    description: Better Game Mode command.
  test:
    usage: /test
    description: Better Game Mode command.
  reset:
    usage: /reset <Player>
    description: Resets the given player.
  createarmor:
    usage: /createarmor <args>
    description: Create Armor
  createsword:
    usage: /createsword <args>
    description: Create Swords.
  sbenchant:
    usage: /sbenchant <Enchantment> <Level>
    description: Enchant the item you're holding!
  convertitem:
    usage: /convertitem
    description: Converts the item you're holding!
  recombobulate:
    usage: /recombobulate
    description: Recombobulates the item you're holding!
  reforgemenu:
    usage: /reforgemenu
    description: Opens the reforge menu without the blacksmith!